const tasks = [
    {
        imgURL: "fall.jpg",
        title: "Fall Cleanup",
        instructions: [ 
                "Check for vegetation near the buildings that needs to be trimmed back to prevent dampness from developing. ",
                "Check if any roots are causing damage to paths, roads, or the building foundation.", 
                "Check the entire property for signs of soil erosion and ensure drainage channels are not being filled by natural soil movement.",
                "Rake leaves and dispose of properly.",
                "Remove spider webs, insect debris, and dirt from exterior of building.",
                "Remove weeds and invasive plant growth.", 
                "Remove bird/animal nests from areas where damage to buildings or structures could occur.",
                "Remove dead plant growth.",
                "Inspect the trees for loose, rotted, or dead limbs that could fall. Verify that there are no limbs that could fall  onto the roof and that the trees are trimmed back and away from the building.", 
                "Winterize hose bibs.",
                "Drain garden hoses and store properly.",
                "Clean out all eaves, gutters, and drains.",
                "Apply a winter fertilizer to lawn areas. (optional)"
        ],
        lastCompleted: "11/9/2025",
        dueDate: "11/9/2026",
        frequency: "Yearly",
    },
        {
        imgURL: "spring.jpg",
        title: "Spring Cleanup",
        instructions: [ 
                "Check for vegetation near the buildings that needs to be trimmed back to prevent dampness from developing. ",
                "Check if any roots are causing damage to paths, roads, or the building foundation.", 
                "Check the entire property for signs of soil erosion and ensure drainage channels are not being filled by natural soil movement.",
                "Sweep driveways and paved areas.",
                "Power-wash sidewalks, driveways, and paved areas, if needed.",
                "Check all culverts and swales from blockage, making sure that water drains properly.",
                "Make sure vegetation is not growing over sidewalks or parking areas.", 
                "Remove bird/animal nests from areas where damage to buildings or structures could occur.",
                "Inspect the trees for loose, rotted, or dead limbs that could fall. Verify that there are no limbs that could fall onto the roof and that the trees are trimmed back and away from the building.", 
                "Check all exterior hose bibs.",
                "Inspect any decorative landscape edging to confirm that it is in good condition.",
                "Check the mulch condition: refresh annually, or as needed.  Verify that the mulch height is 4-6” below the sill plate of the building and that the grade allows for drainage away from the building.",
                "Verify that bushes, hedges, or small trees are well-manicured and free of disease.",
                "Repair lawn damage.",
                "Apply spring fertilizer. (optional)",
                "Paint or repaint fire lane curb.",
                "Clean vegetation from around A/C units.",
                "Weed and landscape both upper and lower gate walls."
        ],
        lastCompleted: "4/5/2025",
        dueDate: "4/5/2026",
        frequency: "Yearly",
    },
      {
        imgURL: "carpet.jpg",
        title: "Carpets & Mats",
        instructions: [ 
                "Are entry floor mats in good condition without curled-up edges and fixed in a position so as not to slide around?",
                "Make sure that floors are even and carpets are free of wrinkles.", 
                "Inspect carpet for tears, lifting along edges, bubbling, or significant wear (especially in high-traffic areas).",
                "Remove chairs, if possible, and clean the carpets using commercial-grade carpet cleaners.",
                "THOROUGHLY dry carpet with fans before re-setting chairs.","Ensure that all mats are sufficient in size to remove moisture/dirt from shoes.",
                "Clean the mats using commercial-grade carpet cleaners."
        ],
        lastCompleted: "11/6/2025",
        dueDate: "5/6/2026",
        frequency: "6 Months",
    },
]